fix(eslint-config): split into two groups and add newline between groups
dhis2/cli-style pull request #304
Opened 2020-10-19 15:18 UTC by HendrikThePendric

I prefer this config because:
- This creates two main groups, basically "internal" vs "others"
- Between these two groups we'll get a newline

Current sort result:
```
import i18n from '@dhis2/d2-i18n'
import propTypes from '@dhis2/prop-types'
import MailIcon from 'material-ui-icons/MailOutline'
import Subheader from 'material-ui/Subheader/Subheader'
import React, { Component } from 'react'
import { connect } from 'react-redux'
import { compose } from 'recompose'
import Toolbar from '../Common/Toolbar'
import MessageConversationList from '../List/MessageConversationList'
import SidebarList from '../List/SidebarList'
import CreateMessage from '../MessageConversation/CreateMessage'
import MessageConversation from '../MessageConversation/MessageConversation'
import './MessagingCenter.css'
```

Improved sort result:
```
import i18n from '@dhis2/d2-i18n'
import propTypes from '@dhis2/prop-types'
import MailIcon from 'material-ui-icons/MailOutline'
import Subheader from 'material-ui/Subheader/Subheader'
import React, { Component } from 'react'
import { connect } from 'react-redux'
import { compose } from 'recompose'

import Toolbar from '../Common/Toolbar'
import MessageConversationList from '../List/MessageConversationList'
import SidebarList from '../List/SidebarList'
import CreateMessage from '../MessageConversation/CreateMessage'
import MessageConversation from '../MessageConversation/MessageConversation'
import './MessagingCenter.css'
```

FYI: this is a PR against `alpha`.

2020-10-19 15:30 UTC, varl commented
I like the aesthetics of newlines between groups. The main argument against it is that `always` allows for this to happen, and cannot fix it:

```
import i18n from '@dhis2/d2-i18n'
import propTypes from '@dhis2/prop-types'
import { connect } from 'react-redux'
import { compose } from 'recompose'




import Toolbar from '../Common/Toolbar'
import MessageConversationList from '../List/MessageConversationList'
import SidebarList from '../List/SidebarList'
```

2020-10-20 08:32 UTC, HendrikThePendric commented
> The main argument against it is that `always` allows for this to happen, and cannot automatically fix it:

Did you verify this on your local machine? I've tried my config and to me it seems the problem you have identified isn't occurring:
Initial state:
![Screenshot 2020-10-20 at 10 25 44](https://user-images.githubusercontent.com/353236/96560874-255f7b00-12bf-11eb-975d-d8699a167946.png)

After formatting:
![Screenshot 2020-10-20 at 10 27 34](https://user-images.githubusercontent.com/353236/96560949-38724b00-12bf-11eb-8700-73ccec0c1a36.png)

2020-10-20 08:40 UTC, ismay commented
> I'm not opposed to changing this rule. There is value in that never is always consistent and we never had to think about it again ... at the price of it being a dense block.

Yeah personally I prefer the readability of a single block. With the newline between groups, if there are only two imports for example, one in each group, you'll have `import, newline, import, newline, code`. That makes the code more difficult to scan for me.

Whereas a single block is always a single block. And you can rely on the ordering to see whether something is remote or local. Plus the newlines between become less useful with multiple groups, because it compounds the above issue.

But that's my personal preference.

2020-10-20 08:51 UTC, varl commented
@HendrikThePendric 

Interesting! You're right. Their documentation on that option is wrong then:

>If set to `always`, at least one new line between each group will be enforced, and new lines inside a group will be forbidden. To prevent multiple lines between imports, core `no-multiple-empty-lines` rule can be used.

2020-10-20 08:55 UTC, HendrikThePendric commented
> Interesting! You're right.

I love it when that happens, which it was more often. So I guess both configs work OK then. So now we just need to get consensus on whether or not to include the newline. And perhaps discuss the grouping (?).....

How shall we do that? I can just create a quick poll in the frontend channel? This seems to be too nit-picky to create a whole issue for....

2020-10-20 09:01 UTC, varl commented
@ismay 

I think this PR is a middle ground of sorts. It only has a newline between built-in and local imports, not between each internal group.

So this would be annoying as you say:

```
import foo from 'foo'

import bar from '../bar.js'

import fuz from './fuz.js'
```

But this PR would produce:

```
import foo from 'foo'

import bar from '../bar.js'
import fuz from './fuz.js'
```

Since @HendrikThePendric feels strongly enough to create a PR for it, we can give it a go in `alpha` and see if we are OK with it in practice. What do you think, @ismay?

2020-10-20 09:05 UTC, varl commented
@HendrikThePendric I think we can discuss the grouping a bit, since you changed it from the defaults:

```
["builtin", "external", "parent", "sibling", "index"]
```

I would expect:

```
[
  [ "builtin", "external" ],
  [ "parent", "sibling", "index" ]
]
```

But this PR went with:

```
[
  ['external', 'builtin'],
  ['index', 'sibling', 'parent', 'internal', 'object'],
]
```

Care to expand on this?

2020-10-20 09:14 UTC, varl commented
> How shall we do that? I can just create a quick poll in the frontend channel? This seems to be too nit-picky to create a whole issue for....

Let's discuss it here, then get it into `alpha`, recommend the frontend team to check it out if they care about it at all, and when we think about merging it to `master`, we inform the frontend team that it is the last chance to give feedback _before_ we roll it out.

After rolling out changes are going to be harder to push for.

2020-10-20 09:22 UTC, ismay commented
> Since @HendrikThePendric feels strongly enough to create a PR for it, we can give it a go in `alpha` and see if we are OK with it in practice. What do you think, @ismay?

Sure, that's fine by me. Most important thing to me is the consistency that this plugin introduces (just like with prettier).

About `object` and `internal`. Object is typescript specific, which allows a certain type of import. And internal is if you've configured webpack with a custom resolver for certain internal paths. See also:

<img width="784" alt="Screenshot 2020-10-20 at 11 20 35" src="https://user-images.githubusercontent.com/7355199/96566952-7cb51980-12c6-11eb-9239-8fe7c4629714.png">

2020-10-20 09:52 UTC, HendrikThePendric commented
> Their documentation on that option is wrong

I've reflected on this a bit, and actually I think the docs are correct. They are suggesting to use the `no-multiple-empty-lines` rule from eslint-core to prevent multiple lines. In our case we are doing something similar: in `config/js/eslint.config.js` we are extending from `prettier` and using the `prettier` plugin. This is removing the newlines for us. (i.e. I get this error when linting a file with multiple newlines:
```
Delete `⏎⏎⏎⏎⏎⏎⏎` [Error/prettier/prettier]
```

I would argue that this isn't a problem, because both configurations are in the same file.

----

Moving on to the grouping...



> But this PR went with:
> 
> ```
> [
>   ['external', 'builtin'],
>   ['index', 'sibling', 'parent', 'internal', 'object'],
> ]
> ```
> 
> Care to expand on this?

Yes I can expand a little bit on this. I would really like to end up with a config where we only have two groups. And I like having a "mine VS theirs" / "internal VS external" type of split.

My approach was very simplistic:
1. I took all the available groups, since I don't want surprises
1. Put the ones that definitely weren't internal into the first group...
1. And the the ones that seemed internal to me in the second group
1. I assumed that the item-order within a group-array did not have an effect. And judging by the output I am showing in https://github.com/dhis2/cli-style/pull/304#issuecomment-712687545 I don't think it does*.

So, assuming order within a group isn't relevant, the only difference between the config you suggested and my own is the addition of `internal` and `object`. These probably aren't relevant but we could just keep them in for completeness.

[*] I think it's probably important to emphasise the implications of this point. Given that we have essentially moved from 5 groups (the default) to just two groups, we need to realise that within these groups imports will be sorted alphabetically. This will have the following effect:
- In the first group we will see a mix of external and builtin imports, all sorted alphabetically.
- The same will happen in the second group, but since in practice these will almost always be relative imports the effect is a bit different. Since the period `.` and forward slash `/` are before `a` we will see sequences like the one in https://github.com/dhis2/cli-style/pull/304#issuecomment-712687545 where imports from folders higher up in the hierarchy come first and siblings come last.

To me this is fine, but I can imagine that others might prefer to have a specific order within these "meta-groups". If this is the case, we should just go with the current config and close this PR, because I don't think it can be done.

2020-10-20 11:29 UTC, varl commented
> This is removing the newlines for us. (i.e. I get this error when linting a file with multiple newlines:

Oh nice, perfect!

> To me this is fine, but I can imagine that others might prefer to have a specific order within these "meta-groups". If this is the case, we should just go with the current config and close this PR, because I don't think it can be done.

That's a shame. The order within the meta groups is important to me, not just alphabetically.

2020-10-20 11:47 UTC, varl requested changes
Ok, since it is not possible to sort the "groups" within the "meta groups" I vote that we close this. Thanks for explaining the consequences clearly, @HendrikThePendric. I didn't properly understand that it was just alphabetical within the "meta groups" and not "meta groups > groups > alphabetical".

2020-10-20 12:29 UTC, HendrikThePendric commented
So, I guess this was a worthwhile experiment. We explored alternative options and after long deliberation concluded that what we have already is better. Closing this PR now.

2020-10-20 12:29 UTC, closed without merging

2020-10-20 12:35 UTC, varl commented
@HendrikThePendric this experiment also showed that if we want to, we can use `always` for the newlines between groups setting because we already have Prettier that enforces a single newline and removes multiple newlines automatically, and we don't have to add anything new to handle that case. :+1: