feat(husky): update pot files before commit
dhis2/cli-style pull request #312
Opened 2020-11-05 14:46 UTC by HendrikThePendric

Not sure if this is a good idea, but if it is pls hit approve. Also see [this Slack thread](https://dhis2.slack.com/archives/CHENB0272/p1604583935002500) for context.

2020-11-05 15:15 UTC, varl commented
We need to keep in mind that `d2-style` is used in non-app and non-i18n contexts as well, so the default configuration is intentionally generic so that it is compatible with all our JS code.

Option 1 is to customize the `.huskyrc.js` in the apps were `app-platform` is used.

Option 2 is create a new "app"  template for the git hooks in `d2-style`. The same way we have solved the React-eslint vs. Vanilla-eslint setups here.

As this PR is right now, it will not work for us.

2020-11-05 15:17 UTC, varl commented
Maybe an "app" here: https://github.com/dhis2/cli-style/blob/master/src/utils/groups.js#L106-L126

2020-11-11 13:01 UTC, HendrikThePendric commented
@varl thanks for the comments above. I tried following your instructions to the letter, mainly because that was quicker than getting completely familiarised with how `cli-style` works. Could you review the revised implementation?

2020-11-24 08:59 UTC, amcgee requested changes

2020-11-24 08:59 UTC, amcgee commented on config/husky-app.local.js
> +            'd2-app-scripts i18n',
This needs to be `d2-app-scripts i18n extract && d2-app-script i18n generate`, I believe

2020-11-24 09:06 UTC, amcgee commented on config/husky-app.local.js
> +            'd2-app-scripts i18n',
Actually only `extract` is required, technically

2021-02-10 15:06 UTC, HendrikThePendric commented
@varl @amcgee this PR has been open for a very long time. I think it's slipped off the radar. It's not really a crucial fix and if I've understood things correctly it will become redundant once we revamp the translation mechanism as a whole. So I'd be happy to just close this issue.

2021-02-11 23:18 UTC, amcgee commented
@HendrikThePendric yeah, I think that's fair - sorry it got stale.  This problem should go away when we get rid of source-generated translations.

2021-02-11 23:18 UTC, closed without merging